name: go-action
description: simple go docker based action
inputs:
  whogreet:
    description: who to greet
    required: true
    default: world
outputs:
  message:
    description: greeting message
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.whogreet }}
